service: upload-image

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline

functions:
  getUploadUrl:
    handler: handler.getUploadUrl
    events:
      - http:
          path: /
          method: get

# The below section can allow you to create the S3 bucket on function deployment. Make sure you change bucket name tho

# resources:
#   Resources:
#     Storage:
#       Type: 'AWS::S3::Bucket'
#       Properties:
#         BucketName: tipputhynhean-sls-uploadimage-demo
#         CorsConfiguration:
#           CorsRules:
#             -
#               AllowedOrigins:
#                 - '*'
#               AllowedHeaders:
#                 - '*'
#               AllowedMethods:
#                 - PUT
#                 - GET
#                 - HEAD
#                 - POST
#               MaxAge: 3000